#!/bin/bash

## test case for heaving wing from Sugar-Gabor, 2018, doi:
## 10.1017/aer.2018.57

SOLVE=../../tools/llt-solve
## flight velocity
U=40
## pitch oscillation frequency
Om=26.247
##Om=78.74
## heave oscillation amplitude
h=0.0508
##h=0.0254

${SOLVE} -H ${h} -L wing.llt -n 128 -O ${Om} -s naca0012.sec -t 0 -T 0.9 \
	 -U ${U} -w > cl.dat
