LLT: amc.c File Reference
amc.c File Reference
Functions
amc_transform_t * amc_transform_alloc (int dim, int order)
int amc_transform_entry_set (amc_transform_t *T, int order, int i, int j, double val, char *str)
int amc_transform_matrix_write (FILE *f, amc_transform_t *T, int order)
int amc_transform_expressions_compile (amc_transform_t *T)
int amc_transform_matrix_apply (amc_transform_t *T, int order, double *xin, double *xout)
int amc_transform_matrix_apply_vector (amc_transform_t *T, int order, double *xin, double *n, double *xout)
int amc_transform_matrices_evaluate (amc_transform_t *T, double t)
int amc_transform_variable_add (amc_transform_t *T, char *str, double *adr)
int amc_transform_variables_write (FILE *f, amc_transform_t *T)
amc_transform_chain_t * amc_transform_chain_alloc (int ntrans)
int amc_transform_chain_transform_add (amc_transform_chain_t *C, amc_transform_t *T)
int amc_transform_matrix_identity (amc_transform_t *T, int order)
int amc_transform_matrix_zero (amc_transform_t *T, int order)
int amc_transform_chain_evaluate (amc_transform_chain_t *C, int order, amc_transform_t *T)
int amc_transform_chain_derivative (amc_transform_chain_t *C, int order, amc_transform_t *S, double t, double *x, double *dx)
int amc_transform_translation (amc_transform_t *T, double dx, char *xstr, double dy, char *ystr, double dz, char *zstr, int order)
int amc_transform_rotation (amc_transform_t *T, double th, char *str, int order)
int amc_transform_rotation_x (amc_transform_t *T, double th, char *str, int order)
int amc_transform_rotation_y (amc_transform_t *T, double th, char *str, int order)
int amc_transform_rotation_z (amc_transform_t *T, double th, char *str, int order)
int amc_transform_derivatives_evaluate (amc_transform_t *T, int order)
int amc_transform_derivative_check (amc_transform_t *T, int order, double t, double dt, int *imax, double *emax)
int amc_transform_chain_matrices_evaluate (amc_transform_chain_t *C, double t, amc_transform_t *T, int order)
Detailed Description
Author
micha.nosp@m.el@m.nosp@m.ichae.nosp@m.l.pa.nosp@m.raffi.nosp@m.nali.nosp@m.a.co..nosp@m.uk
Date
Fri May 17 09:08:48 2024
Function Documentation
amc_transform_alloc()
amc_transform_t * amc_transform_alloc (int dim, int order)
Allocate an AMC transform of dimension dim and maximum derivative order order
Parameters
dim dimension of transform (must be two or three);
order highest order of time derivative of transform to be evaluated.
Returns
newly allocated ::amc_transform_t
References amc_transform_variable_add().
amc_transform_chain_alloc()
amc_transform_chain_t * amc_transform_chain_alloc (int ntrans)
Allocate a transform chain, a sequence of transforms to be applied successively
Parameters
ntrans maximum number of transforms in chain.
Returns
newly allocated ::amc_transform_chain_t.
amc_transform_chain_derivative()
int amc_transform_chain_derivative (amc_transform_chain_t * C, int order, amc_transform_t * S, double t, double * x, double * dx)
Numerically estimate derivative of transformed point
Parameters
C an ::amc_transform_chain_t;
order order of derivatives to evaluate;
S workspace for transform;
t time for evaluation;
x input point;
dx on output contains estimated time derivative of transform of x.
Returns
0 on success.
References amc_transform_chain_evaluate(), amc_transform_matrices_evaluate(), and amc_transform_matrix_apply().
amc_transform_chain_evaluate()
int amc_transform_chain_evaluate (amc_transform_chain_t * C, int order, amc_transform_t * T)
Evaluate a sequence of transforms in a chain, including time derivatives
Parameters
C chain of transforms, which have been evaluated at required time;
order maximum derivative to evaluate;
T on exit, contains sequence of transforms, including time derivatives.
Returns
0 on success.
Referenced by amc_transform_chain_derivative(), and amc_transform_chain_matrices_evaluate().
amc_transform_chain_matrices_evaluate()
int amc_transform_chain_matrices_evaluate (amc_transform_chain_t * C, double t, amc_transform_t * T, int order)
Convenience function to evaluate matrices in a chain
Parameters
C ::amc_transform_chain_t containing transforms;
t evaluation time;
T if not NULL, is set to transform found by applying whole chain;
order order of derivatives to generate in T.
Returns
0 on success
References amc_transform_chain_evaluate(), and amc_transform_matrices_evaluate().
amc_transform_chain_transform_add()
int amc_transform_chain_transform_add (amc_transform_chain_t * C, amc_transform_t * T)
Add a transform to a chain of transforms
Parameters
C an allocated ::amc_transform_chain_t;
T ::amc_transform_t to be added to chain.
Returns
0 on success, or 1 if the maximum number of transforms in C has been reached.
amc_transform_derivative_check()
int amc_transform_derivative_check (amc_transform_t * T, int order, double t, double dt, int * imax, double * emax)
Check symbolically evaluated derivatives of transform against numerical estimate
Parameters
T an ::amc_transform_t;
order order of derivative to check;
t evaluation time;
dt for finite difference estimate of derivative;
imax on exit contains index of entry with largest difference between numerical estimate and symbolically evaluated derivative;
emax on exit contains largest difference between numerical estimate and symbolically evaluated derivative;
Returns
0 on success
amc_transform_derivatives_evaluate()
int amc_transform_derivatives_evaluate (amc_transform_t * T, int order)
Evaluate derivatives of a transform up to some specified order by symbolic differentiation of expressions for transform matrix. This requires that the libmatheval library be installed.
Parameters
T an ::amc_transform_t;
order maximum order of derivative to evaluate.
Returns
0 on success.
Referenced by amc_transform_rotation(), amc_transform_rotation_x(), amc_transform_rotation_y(), amc_transform_rotation_z(), and amc_transform_translation().
amc_transform_entry_set()
int amc_transform_entry_set (amc_transform_t * T, int order, int i, int j, double val, char * str)
Set an element of a transform as symbolic expression or numerical constant
Parameters
T ::amc_transform_t
order derivative order whose element is to be set
i row index of element (less than three for two-dimensional transform, less than four for three-dimensional);
j column index of element (less than three for two-dimensional transform, less than four for three-dimensional);
val numerical value of element;
str if not NULL, symbolic expression for element, which will be evaluated using parser at each time, overwriting val, and which can be symbolically differentiated.
Returns
0 on success.
Referenced by amc_transform_rotation(), amc_transform_rotation_x(), amc_transform_rotation_y(), amc_transform_rotation_z(), and amc_transform_translation().
amc_transform_expressions_compile()
int amc_transform_expressions_compile (amc_transform_t * T)
Compile symbolic expressions in a transform for future evaluation. This must be done after symbolic expressions are defined and before evaluating or applying the transform.
Parameters
T an ::amc_transform_t;
Returns
0 on success.
amc_transform_matrices_evaluate()
int amc_transform_matrices_evaluate (amc_transform_t * T, double t)
Evaluate numerical values of transform matrices for all derivatives up to maximum defined order of T
Parameters
T an ::amc_transform_t;
t time for evaluation.
Returns
0 on success.
Referenced by amc_transform_chain_derivative(), and amc_transform_chain_matrices_evaluate().
amc_transform_matrix_apply()
int amc_transform_matrix_apply (amc_transform_t * T, int order, double * xin, double * xout)
Apply a transform to a point
Parameters
T ::amc_transform_t to apply;
order order of derivative of T;
xin input point;
xout output point (can be the same as xin).
Returns
0 on success.
Referenced by amc_transform_chain_derivative().
amc_transform_matrix_apply_vector()
int amc_transform_matrix_apply_vector (amc_transform_t * T, int order, double * xin, double * n, double * xout)
Apply a transform to a vector (such as a unit normal)
Parameters
T ::amc_transform_t to apply;
order order of derivative of T;
xin origin of vector;
n vector;
xout output vector (can be the same as xin).
Returns
0 on success.
amc_transform_matrix_identity()
int amc_transform_matrix_identity (amc_transform_t * T, int order)
Set a transform to the identity matrix
Parameters
T an ::amc_transform_t;
order derivative whose matrix is to be set to identity.
Returns
0 on success.
Referenced by amc_transform_rotation(), amc_transform_rotation_x(), amc_transform_rotation_y(), amc_transform_rotation_z(), and amc_transform_translation().
amc_transform_matrix_write()
int amc_transform_matrix_write (FILE * f, amc_transform_t * T, int order)
Write elements of the derivative of a transform matrix to file
Parameters
f file stream for output;
T ::amc_transform_t whose entries are to be written;
order derivative order whose entries are to be written.
Returns
0 on success.
amc_transform_matrix_zero()
int amc_transform_matrix_zero (amc_transform_t * T, int order)
Set a transform matrix to all zeros.
Parameters
T an ::amc_transform_t
order derivative whose matrix entries are to be set to zero.
Returns
0 on success.
Referenced by amc_transform_rotation(), amc_transform_rotation_x(), amc_transform_rotation_y(), amc_transform_rotation_z(), and amc_transform_translation().
amc_transform_rotation()
int amc_transform_rotation (amc_transform_t * T, double th, char * str, int order)
Set two-dimensional transform to rotation in - plane
Parameters
T ::amc_transform_t to set;
th rotation angle ;
str if not NULL, symbolic expression for , which overrides numerical value th;
order maximum order of derivatives to evaluate.
Returns
0 on success.
References amc_transform_derivatives_evaluate(), amc_transform_entry_set(), amc_transform_matrix_identity(), and amc_transform_matrix_zero().
amc_transform_rotation_x()
int amc_transform_rotation_x (amc_transform_t * T, double th, char * str, int order)
Set three-dimensional transform to rotation about axis
Parameters
T ::amc_transform_t to set;
th rotation angle about axis;
str if not NULL, symbolic expression for , which overrides numerical value th;
order maximum order of derivatives to evaluate.
Returns
0 on success.
References amc_transform_derivatives_evaluate(), amc_transform_entry_set(), amc_transform_matrix_identity(), and amc_transform_matrix_zero().
amc_transform_rotation_y()
int amc_transform_rotation_y (amc_transform_t * T, double th, char * str, int order)
Set three-dimensional transform to rotation about axis
Parameters
T ::amc_transform_t to set;
th rotation angle about axis;
str if not NULL, symbolic expression for , which overrides numerical value th;
order maximum order of derivatives to evaluate.
Returns
0 on success.
References amc_transform_derivatives_evaluate(), amc_transform_entry_set(), amc_transform_matrix_identity(), and amc_transform_matrix_zero().
amc_transform_rotation_z()
int amc_transform_rotation_z (amc_transform_t * T, double th, char * str, int order)
Set three-dimensional transform to rotation about axis
Parameters
T ::amc_transform_t to set;
th rotation angle about axis;
str if not NULL, symbolic expression for , which overrides numerical value th;
order maximum order of derivatives to evaluate.
Returns
0 on success.
References amc_transform_derivatives_evaluate(), amc_transform_entry_set(), amc_transform_matrix_identity(), and amc_transform_matrix_zero().
amc_transform_translation()
int amc_transform_translation (amc_transform_t * T, double dx, char * xstr, double dy, char * ystr, double dz, char * zstr, int order)
Set transform to translation by possibly time-dependent displacement
Parameters
T ::amc_transform_t to set;
dx displacement;
xstr if not NULL, symbolic expression for dx;
dy displacement;
ystr if not NULL, symbolic expression for dy;
dz displacement (ignored for two-dimensional transform);
zstr if not NULL, symbolic expression for dz (ignored for two-dimensional transform);
order maximum order of derivatives to evaluate.
Returns
0 on success.
References amc_transform_derivatives_evaluate(), amc_transform_entry_set(), amc_transform_matrix_identity(), and amc_transform_matrix_zero().
amc_transform_variable_add()
int amc_transform_variable_add (amc_transform_t * T, char * str, double * adr)
Add a symbolic variable to a transform.
Parameters
T an ::amc_transform_t;
str name of variable;
adr pointer to address of variable for compilation and evaluation.
Returns
0 on success.
Referenced by amc_transform_alloc().
amc_transform_variables_write()
int amc_transform_variables_write (FILE * f, amc_transform_t * T)
Write variables defined in a transform to file.
Parameters
f output file stream;
T an ::amc_transform_t whose variables are to be listed.
Returns
0 on success.