LLT: Vortex lattices
Vortex lattices
Functions
llt_lattice_t * llt_lattice_alloc (gint np, gint nt)
gint llt_lattice_velocity (llt_lattice_t *l, gdouble d, gdouble *x, gdouble al, gdouble bt, gdouble *u)
gint llt_lattice_velocity_lifting_line (llt_lattice_t *W, llt_lifting_line_t *L, gdouble d, gdouble *u, gint ustr)
gint llt_lattice_write (FILE *f, llt_lattice_t *W)
gint llt_lattice_initialise (llt_lattice_t *W, llt_lifting_line_t *L, gdouble t, double G0)
gint llt_lattice_wake_shed (llt_lattice_t *W, llt_lifting_line_t *L, gdouble t)
gint llt_lattice_velocity_lattice (llt_lattice_t *S, llt_lattice_t *T, gdouble d, gdouble al, gdouble bt, gdouble *u, gint ustr)
gdouble llt_lattice_ring_length (llt_lattice_t *l, gint i, gint j)
Detailed Description
Function Documentation
llt_lattice_alloc()
llt_lattice_t * llt_lattice_alloc (gint np, gint nt)
Allocate a lattice to store wake data
Parameters
np (maximum) number of points on lattice edge: this should be equal to the number of wake (trailing edge) points on the lifting line shedding the wake;
nt (maximum) number of time steps (shed rows) in lattice.
Returns
newly allocated ::llt_lattice_t
llt_lattice_initialise()
gint llt_lattice_initialise (llt_lattice_t * W, llt_lifting_line_t * L, gdouble t, double G0)
Initialise a vortex lattice by connection to a lifting line
Parameters
W vortex lattice;
L lifting line from which vortex lattice in W is being shed;
t initial time;
G0 initial circulation.
Returns
0 on success.
llt_lattice_ring_length()
gdouble llt_lattice_ring_length (llt_lattice_t * l, gint i, gint j)
Convenience function for length of vortex ring in lattice
Parameters
l an ::llt_lattice_t;
i time step when vortex ring was shed;
j index of point from which vortex ring was shed.
Returns
length of vortex ring with corner at point .
llt_lattice_velocity()
gint llt_lattice_velocity (llt_lattice_t * l, gdouble d, gdouble * x, gdouble al, gdouble bt, gdouble * u)
Evaluate velocity induced by lattice at field point
Parameters
l vortex lattice;
d regularization parameter for velocity evaluation;
x field point for evaluation of velocity;
al scaling factor for lattice velocity;
bt scaling factor for initial velocity;
u on entry contains , on exit contains with velocity generated by lattice l.
Returns
0 on success.
Referenced by llt_lattice_velocity_lattice(), and llt_lattice_velocity_lifting_line().
llt_lattice_velocity_lattice()
gint llt_lattice_velocity_lattice (llt_lattice_t * S, llt_lattice_t * T, gdouble d, gdouble al, gdouble bt, gdouble * u, gint ustr)
Evaluate velocity "induced" by one vortex lattice on another lattice
Parameters
S source lattice;
T target lattice;
d regularisation parameter;
al ;
bt ;
u on entry contains , on exit contains with velocity generated by lattice S;
ustr stride in u.
Returns
0 on success.
References llt_lattice_velocity().
llt_lattice_velocity_lifting_line()
gint llt_lattice_velocity_lifting_line (llt_lattice_t * W, llt_lifting_line_t * L, gdouble d, gdouble * u, gint ustr)
Evaluate lattice-induced velocity at each collocation point of a lifting line
Parameters
W lattice (wake);
L lifting line;
d regularization parameter for velocity evaluation;
u pointer to array of velocities;
ustr stride between successive velocities.
Returns
0 on success.
References llt_lattice_velocity().
llt_lattice_wake_shed()
gint llt_lattice_wake_shed (llt_lattice_t * W, llt_lifting_line_t * L, gdouble t)
Update a vortex lattice by adding shed vorticity from a lifting line
Parameters
W wake lattice;
L lifting line generating wake in W;
t shedding time (used to calculate viscous effects).
Returns
0 on success.
llt_lattice_write()
gint llt_lattice_write (FILE * f, llt_lattice_t * W)
Write vortex lattice data to output as nodes of lattice and circulations
Parameters
f output file stream;
W lattice to write.
Returns
0 on success.